### ISSUE TITLE
RFE: Document how to setup bluetooth connection

### ISSUE THREAD

**Issue by tyll** [brandonarbini/treadmill#2]
I tried to use this to access a LifeSpan TR1200-DT3. Using bluetoothctl, I can connect to the treadmill and rfcomm seems to allow to do something in relationship of a tty but when I point the tool to a created device node, it just hangs. A little bit more guidance would be great. If you have some rough notes, I am happy to organize them as a proper documentation in a PR.

**Comment by brandonarbini** [comment]
It has been a long time since I used this actually. I'll try it again as soon as I head back to the office and have time.

**Comment by lkonya** [comment]
Any update on this?

**Comment by jgreer** [comment]
It's been a long time since either of us have touched this (I don't have a treadmill anymore).  All it took in the past was connecting the bluetooth (which you can do for a short period of time after powering on the treadmill), and it would create the serial device automatically.  I think the filename may have changed at some point.  It's also possible that the protocol from newer firmware has changed.

The version of the code I used to run daily was just using the original script I wrote, but looping and showing updated stats as you used it.  It wasn't based on the gem version, but it was updated to try finding the serial port even if the filename was a bit different...  I'll attach that here, in case it's useful.

[treadmill_display.rb.zip](https://github.com/brandonarbini/treadmill/files/9841921/treadmill_display.rb.zip)

**Comment by tyll** [comment]
Thanks @jgreer - what exactly do you mean with "Connecting the bluetooth" - did you connect to it using gnome-control-center? Are you using MacOS? Or Windows?

**Comment by jgreer** [comment]
I've only used it on a mac...  But I think the same applies for Windows.  I can't remember if it's pairable when you first turn it on or if you have to hit the bluetooth button...  Anyway, just like any other bluetooth device, on the computer I go to the bluetooth preferences and wait for it to show in the list and click connect.  I couldn't say what the right process is on Linux, but in my experience when it connects, it automatically creates the serial device under `/dev/`

**Comment by tyll** [comment]
Thank you. I guess it is just different with my treadmill, it might be using BLE. Or it is different on Linux.
